#!/bin/sh
if [ $# -lt 1 ]; then
    echo "usage: $0 [init|dev|prod]"
    exit
fi

target=$1
engine="innodb"
migrate_path="log/models.migrate"
meta_path="src/meta";

script_dir=$(dirname pwd);
cd ${script_dir};

sql_file="${migrate_path}/database.sql"

if [ "${target}" = "init" ]; then
    rm -rf ${migrate_path}
    mkdir "${migrate_path}"
    mkdir "${migrate_path}/dev"
    mkdir "${migrate_path}/prod"
    
    touch "${migrate_path}/dev/migration"
    touch "${migrate_path}/dev/database"
    touch "${migrate_path}/prod/migration"
    touch "${migrate_path}/prod/database"
    
    md5sum ${meta_path}/dev/* > "${migrate_path}/dev/migration"
    md5sum ${meta_path}/prod/* > "${migrate_path}/prod/migration"

    for meta in	`ls src/meta/dev/*meta.xml`
    do
	meta_name=`basename ${meta}`
	table_name=${meta_name/.meta.xml/}
	meta_name="src/meta/dev/${table_name}.meta.xml"
	router_name="src/meta/dev/${table_name}.router.xml"
	mpic_sql ${meta_name} ${router_name} ${engine} >> "${migrate_path}/dev/create.sql"
    done

    for file in `ls src/meta/prod/*meta.xml`
    do
	meta_name=`basename ${meta}`
	table_name=${meta_name/.meta.xml/}
	meta_name="src/meta/prod/${table_name}.meta.xml"
	router_name="src/meta/prod/${table_name}.router.xml"
	mpic_sql ${meta_name} ${router_name} ${engine} >> "${migrate_path}/prod/create.sql"
    done
    echo `cat ${migrate_path}/dev/create.sql | grep DATABASE | awk '{print $3}' | sed 's/;//' | sort -u` > "${migrate_path}/dev/database"
    echo `cat ${migrate_path}/prod/create.sql | grep DATABASE | awk '{print $3}' | sed 's/;//' | sort -u` > "${migrate_path}/prod/database"

    echo "init done"

    exit;
fi

temp=""
result=`md5sum --check ${migrate_path}/${target}/migration | grep 'FAILED' | grep -v 'FAILED open or read' | awk '{print $1}'`
for meta in ${result}
do
    name=`basename ${meta}`
    name=${name/.meta.xml:/}
    table=${name/.router.xml:/}
    if [ "`echo ${temp} | grep ${table}`" = "" ];then
	temp=${temp}" ${table}"
    fi
done


meta_files=`ls src/meta/${target}/*meta.xml`
dirname="src/meta/${target}/"
for meta in ${meta_files}
do
    base_name=`basename ${meta}`
    table=${base_name/.meta.xml/}
    meta_name="${dirname}${table}.meta.xml"
    router_name="${dirname}${table}.router.xml"

    if [ "`cat ${migrate_path}/${target}/migration | grep ${meta_name}`" = "" -o "`cat ${migrate_path}/${target}/migration | grep ${router_name}`" = "" ]; then
	temp=${temp}" ${table}"
    fi
done

true > ${sql_file}
for table in ${temp}
do
    meta_name="${dirname}${table}.meta.xml"
    router_name="${dirname}${table}.router.xml"
    mpic_sql ${meta_name} ${router_name} ${engine} >> ${sql_file}
done

sql=`cat ${sql_file}`
for database in `cat ${migrate_path}/${target}/database`
do
    sed -i "s/CREATE DATABASE ${database};//" ${sql_file}
done

new_databases=`cat ${sql_file} | grep DATABASE | awk '{print $3}' | sed 's/;//' | sort -u`
for new_database in ${new_databases}
do
    echo "${new_database} " >> "${migrate_path}/${target}/database"
    sed -i "/\<CREATE DATABASE ${new_database}\>/!n;0,/\<CREATE DATABASE ${new_database}\>/p;/\<CREATE DATABASE ${new_database}\>/d" ${sql_file}
done

md5sum ${meta_path}/${target}/* > "${migrate_path}/${target}/migration"

echo "finish, source log/models.migrate/database.sql to your database"
