#!/usr/bin/env bash

# 这是一个刚安装完系统，自动安装一些常用软件的脚本
# 首先应该自己已经安装好git了

# 更新源和更新现在所安装的软件
sudo apt-get udpate
sudo apt-get upgrade

# 安装vim7.4
sudo add-apt-repository ppa:fcwu-tw/ppa
sudo apt-get update
sudo apt-get install vim

# 配置vim
cd ~
git clone https://github.com/chloerei/vimrc.git
cd vimrc
./deploy.sh

# 安装nodejs
sudo apt-get install python-software-properties
sudo apt-add-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs
sudo apt-get npm

# 安装curl和wget
sudo apt-get install curl
sudo apt-get install wget

# install php, mysql, apache
sudo apt-get install mysql-server apache2 php5 php5-mysql php-gd
